lemma and_or_distrib_left (P Q R : Prop) : P ∧ (Q ∨ R) ↔ (P ∧ Q) ∨ (P ∧ R) :=
begin
  split,
  intro h,
  cases h with p qor,
  cases qor with q r,
  left,
  split,
  exact p,
  exact q,
  right,
  split,
  exact p,
  exact r,
  intro h,
  cases h with paq par,
  split,
  cases paq with p q,
  exact p,
  cases paq with p q,
  left,
  exact q,
  split,
  cases par with p r,
  exact p,
  cases par with p r,
  right,
  exact r,
end
